
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
symbol.search.limit = 1048576
inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.pyright]
command = "pyright"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true


[[language]]
name = "rust"
formatter = { command = "rustfmt --edition 2021" }


# [[language]]
# name = "elixir"
# scope = "source.elixir"
# file-types = ["ex", "exs"]
# auto-format = true
# diagnostic-severity = "hint"
# comment-token = "#"
# indent = {tab-width = 2, unit = " "}
# injection-regex = "(elixir|ex)"
# shebangs = ["elixir"]
# roots = ["mix.exs", "mix.lock"]
# language-servers = [ "elixir-ls" ]


[language-server.lexical]
command = "/Users/zackdannar/bin/lexical/bin/start_lexical.sh"

[[language]]
name = "elixir"
language-servers = ["lexical"]
file-types = ["ex", "exs"]
auto-format = true
diagnostic-severity = "hint"


[[language]]
name = "heex"
language-servers = ["lexical"]



[[language]]
name = "yaml"
indent = { tab-width = 2, unit = " " }

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "python"
formatter = {command = "black", args = ["--exclude", ".*_pb2.*", "-"]}
auto-format = true

